# Generated by Django 3.2.3 on 2021-06-07 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('prob', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150)),
                ('roll_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(default=None, max_length=150)),
                ('branch', models.CharField(default=None, max_length=10)),
                ('ITW_marks_1', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('ITW_marks_2', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('ITW_marks_3', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('IoT_marks_1', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('IoT_marks_2', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('IoT_marks_3', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('Stats_marks_1', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('Stats_marks_2', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('Stats_marks_3', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('Clang_marks_1', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('Clang_marks_2', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('Clang_marks_3', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('ITW_attendance', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('IoT_attendance', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('Stats_attendance', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
                ('Clang_attendance', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(101)])),
            ],
        ),
    ]
